create table public.book (
  id bigint generated by default as identity not null,
  book_id uuid null default gen_random_uuid (),
  book_title text null,
  author text null,
  isbn text null,
  category text null,
  borrowed_by text null,
  created_at timestamp with time zone null default now(),
  constraint book_pkey primary key (id)
) TABLESPACE pg_default;